[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/posts/index.html"
to = "/resources/"

[[redirects]]
from = "/policies/themes/culture-and-education/index.html"
to = "/policies/themes/culture-education/"

[[redirects]]
from = "/policies/government-geopolitics/index.html"
to = "/policies/themes/governance-geopolitics/"

[[redirects]]
from = "/policies/science-technology/index.html"
to = "/policies/themes/science-technology/"

[[redirects]]
from = "/policies/themes/government-geopolitics/index.html"
to = "/policies/themes/governance-geopolitics/"

[[redirects]]
from = "/projects/index.html"
to = "/policies/"

